export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_REMOVE_ONE = 'CART_REMOVE_ONE'

export const SAVE_SHIPPING = 'SAVE_SHIPPING'

export const SAVE_TOTAL = 'SAVE_TOTAL'

export const SAVE_COUPON = 'SAVE_COUPON'

export const SAVE_SUBTOTAL = 'SAVE_SUBTOTAL'

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
